HW_2 _count_det
shubinsa/made-cpp-2020-hw pull request #2
Opened 2020-09-29 10:39 UTC by shubinsa

2020-10-01 12:11 UTC, SweetWeakness requested changes

2020-10-01 12:11 UTC, SweetWeakness commented on count_det/src/main.s
> +	sub r12, r10, r11
r12 - запрещен
так же нужно восстанавливать значения r4-r11 - для этого используйте пуш и поп

2020-10-01 12:11 UTC, SweetWeakness commented on count_det/src/main.s
> +	pop {r12}
поп есть - собственно где пуш?)

2020-10-02 22:24 UTC, shubinsa commented on count_det/src/main.s
> +	sub r12, r10, r11
Убрал регистр r12
Добавил push

2020-10-02 22:24 UTC, shubinsa commented on count_det/src/main.s
> +	pop {r12}
Добавил push)

2020-10-02 22:25 UTC, shubinsa commented
Убрал регистр r12
Добавил push

2020-10-02 22:27 UTC, merged

2020-10-02 22:38 UTC, shubinsa commented on count_det/src/main.s
> +	sub r12, r10, r11
Убрал регистр r12
Добавил push