Upstream/hw 5 chuck allocator
shubinsa/made-cpp-2020-hw pull request #7
Opened 2020-10-20 16:23 UTC by shubinsa

Домашнее задание №5: chunk_allocator

2020-10-31 23:06 UTC, SweetWeakness requested changes

2020-10-31 23:06 UTC, SweetWeakness commented on chuck_allocator/Allocator.cpp
> +	using rebind = struct rebind { typedef Allocator<T> other; };
ну потому что вот так наверное =)
template <class U>
using rebind = struct rebind { typedef allocator<U> other; };

2020-10-31 23:06 UTC, SweetWeakness commented on chuck_allocator/Allocator.cpp
> +		tail = NULL;
Вам не на xвост соxранять указатель надо, а на голову, и при запросаx аллокации делать соответствующие проxоды начиная с головы.

2020-10-31 23:06 UTC, SweetWeakness commented on chuck_allocator/Allocator.cpp
> +	/*<template typename ...Args>
<template typename ...Args> ну вы что!? 0.0
template <typename ...Args> – правильно.

2020-10-31 23:06 UTC, SweetWeakness commented on chuck_allocator/Allocator.cpp
> +		return new(ptr) T(args...);
std::forward

2020-11-05 21:31 UTC, merged

2020-11-06 17:07 UTC, shubinsa commented
Добрый вечер! Не подскажите, почему ветка закрыта?
Суть в том, что я внёс изменения, и не могу их отправить в этой ветке, хотя комментарии получил 1 ноября и, вроде бы, у меня есть неделя, чтобы их исправить. 
И я не очень понимаю, что сейчас делать: создавать новую ветку с этим заданием, чтобы прикрепить проект?